### ISSUE TITLE
 I want to call your log library in this app and both libraries

### ISSUE THREAD

**Issue by downloadproject** [rbtq/simpleSpdlogWrapper#2]
I have a project that includes an app with two libs (libA, libB), and the app depends on libA and libB. Now I want to call your log library in this app and both libraries. How should I write my cmakelists? thank you!

**Comment by rbtq** [comment]
I have been trying to make it work in premake5 right now but without success, I don't think it works right now. I am not sure how you would add external dependencies for cmake

**Comment by rbtq** [comment]
Right, I have just fixed my library. I am new to making libraries, so I made the error of putting function definitions in .cpp files that were then not found. So first make sure you have the most updated library.

Whilst I am not sure of the exact specifics for cmake, I found for premake5, you needed to include both the spdlogWrapper and spdlog directories found in the simpleSpdlogger directory or it would not work.

![image](https://github.com/user-attachments/assets/8476fd1f-9dca-46bb-8cd2-2bbbc82d0536)

As for using, you need to put it somewhere that can be accessed across the entire program. I found putting it in a seperate file that you then include works just fine.

![image](https://github.com/user-attachments/assets/2b1ca6c5-a09e-4ac6-809d-2ceb13d8c7f0)

And then using it like this.

![image](https://github.com/user-attachments/assets/ab3fca31-e29e-4eef-924b-1a9a22694284)

**Comment by rbtq** [comment]
I have changed how the start function works so in the future when I add more features it wont break existing code, check out readme for more info.

**Comment by rbtq** [comment]
Let me know if you managed to get this working so I can close the issue. Thanks.

**Comment by downloadproject** [comment]
thank you!!
